# Generated by Django 2.2.9 on 2020-01-27 12:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200127_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follewers',
            field=models.ManyToManyField(related_name='_user_follewers_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='_user_following_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
