# Generated by Django 2.2.9 on 2020-01-27 13:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200127_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='follewers',
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(related_name='_user_followers_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
